# Set up the enviornment

The default Python needs to be downgraded to Python 3.7.

In [1]:
# This shows the default Python in Colab
!python -V

Python 3.10.13


[condacolab](https://github.com/conda-incubator/condacolab) provides a simple solution for installing different Python versions using virtual environments.

⚠️ **Notice:** The Colab session will restart after running the next cell. Once the session has restarted, you can proceed with the remaining cells.

In [2]:
!pip install -q condacolab
import condacolab
condacolab.install()

✨🍰✨ Everything looks OK!


Install Python 3.7 using condacolab.

In [3]:
!mamba create -qn myenv python=3.7

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done


In [4]:
!mamba install -qn myenv cudatoolkit=10.2

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... By downloading and using the CUDA Toolkit conda packages, you accept the terms and conditions of the CUDA End User License Agreement (EULA): https://docs.nvidia.com/cuda/eula/index.html

done


Update the default Python path.

In [5]:
!unlink /usr/local/bin/python
!ln -s /usr/local/envs/myenv/bin/python /usr/local/bin/python

import os
os.environ['PATH'] = '/usr/local/envs/myenv/bin:' + os.environ['PATH']
os.environ['LD_LIBRARY_PATH'] = '/usr/local/envs/myenv/lib:' + os.environ['LD_LIBRARY_PATH']

Check that the Python version is downgraded to `3.7`.

In [6]:
!python -V

Python 3.7.12


Install required Python modules.

In [7]:
!python -m pip install -q torch=="1.6.0" dgl-cu102=="0.5.0" numpy=="1.18.5" matplotlib=="3.3.1" scikit-learn=="0.23.2" pyyaml=="6.0.1" ipykernel=="6.16.2" tifffile=="2021.11.2"

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 748.8/748.8 MB 1.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 28.3/28.3 MB 10.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20.1/20.1 MB 16.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.6/11.6 MB 17.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.8/6.8 MB 17.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 670.1/670.1 kB 45.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 138.5/138.5 kB 13.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 178.9/178.9 kB 15.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 167.3/167.3 kB 16.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 84.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 793.8/793.8 kB 46.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 302.2/302.2 kB 24.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Check if GPU is available in PyTorch.

In [8]:
!python -c "import torch; print(torch.cuda.is_available())"

True


Download (clone) the Git repository.

In [9]:
!git clone -b globias https://github.com/ksugar/cell_interaction_gnn.git

Cloning into 'cell_interaction_gnn'...
remote: Enumerating objects: 394, done.
remote: Counting objects: 100% (394/394), done.
remote: Compressing objects: 100% (194/194), done.
remote: Total 394 (delta 179), reused 370 (delta 160), pack-reused 0 (from 0)
Receiving objects: 100% (394/394), 3.73 MiB | 6.90 MiB/s, done.
Resolving deltas: 100% (179/179), done.


Create symbolic links for the modules in the library path so that the Python executable can locate them.

In [10]:
import os
os.environ['PYTHONPATH'] = os.environ['PYTHONPATH'] + ':/content/cell_interaction_gnn/codes'

# Run analysis

## 1. preprocessing

### epidermis

In [11]:
%cd /content/cell_interaction_gnn/analysis/1.preprocessing/epidermis/paw/preprocessing_batch
!python ./run_preprocessing.py

/content/cell_interaction_gnn/analysis/1.preprocessing/epidermis/paw/preprocessing_batch
../../../../../data/epidermis/paw/W-R1/
../../../../../data/epidermis/paw/W-R2/


### simulation

In [12]:
%cd /content/cell_interaction_gnn/analysis/1.preprocessing/simulation/del-div/preprocessing_batch
!python ./run_preprocessing.py

/content/cell_interaction_gnn/analysis/1.preprocessing/simulation/del-div/preprocessing_batch
../../../../../data/simulation/del-div/sample0/
../../../../../data/simulation/del-div/sample1/


## 2. create_network

### epidermis

In [13]:
%cd /content/cell_interaction_gnn/analysis/2.create_network/epidermis/paw/create_network_batch
!python ./run_create_network.py

/content/cell_interaction_gnn/analysis/2.create_network/epidermis/paw/create_network_batch
../../../../../data/epidermis/paw/W-R1/
[360 360   0]
../../../../../data/epidermis/paw/W-R2/
[360 360   0]


In [14]:
%cd /content/cell_interaction_gnn/analysis/2.create_network/epidermis/paw/extract_subnetwork_batch
!python ./run_extract_subnetwork.py

/content/cell_interaction_gnn/analysis/2.create_network/epidermis/paw/extract_subnetwork_batch
../../../../../data/epidermis/paw/W-R1/
[360 360   0]
../../../../../data/epidermis/paw/W-R2/
[360 360   0]


In [15]:
%cd /content/cell_interaction_gnn/analysis/2.create_network/epidermis/paw/load_graph_add_G1perArea_batch
!python ./run_load_graph_add_G1perArea.py

/content/cell_interaction_gnn/analysis/2.create_network/epidermis/paw/load_graph_add_G1perArea_batch
../../../../../data/epidermis/paw/W-R1/
[360 360   0]
../../../../../data/epidermis/paw/W-R2/
[360 360   0]


### simulation

In [16]:
%cd /content/cell_interaction_gnn/analysis/2.create_network/simulation/del-div/create_network_batch
!python ./run_create_network.py

/content/cell_interaction_gnn/analysis/2.create_network/simulation/del-div/create_network_batch
../../../../../data/simulation/del-div/sample0/
[320 320   0]
../../../../../data/simulation/del-div/sample1/
[320 320   0]


In [17]:
%cd /content/cell_interaction_gnn/analysis/2.create_network/simulation/del-div/extract_subnetwork_batch
!python ./run_extract_subnetwork.py

/content/cell_interaction_gnn/analysis/2.create_network/simulation/del-div/extract_subnetwork_batch
../../../../../data/simulation/del-div/sample0/
[320 320   0]
../../../../../data/simulation/del-div/sample1/
[320 320   0]


## 3. training_attribution

### epidermis

#### bidirectional_sum_AG

In [18]:
%cd /content/cell_interaction_gnn/analysis/3.training_attribution/epidermis/paw/bidirectional_sum_AG/run_analyze_prediction_performance
!python ./run_analyze_prediction_performance.py

/content/cell_interaction_gnn/analysis/3.training_attribution/epidermis/paw/bidirectional_sum_AG/run_analyze_prediction_performance


In [ ]:
%cd /content/cell_interaction_gnn/analysis/3.training_attribution/epidermis/paw/bidirectional_sum_AG
!python ./run_training_parallel.py

/content/cell_interaction_gnn/analysis/3.training_attribution/epidermis/paw/bidirectional_sum_AG
0
process id = 4697
1
process id = 4789
2
process id = 4883
3
process id = 4976
4
process id = 5068
5
process id = 5162


In [ ]:
%cd /content/cell_interaction_gnn/analysis/3.training_attribution/epidermis/paw/feature_ZZFR
!python ./run_training_parallel.py

In [ ]:
%cd /content/cell_interaction_gnn/analysis/3.training_attribution/epidermis/paw/feature_ZZFR/bar_plot_attribution_batch
!python ./run_bar_plot_attribution.py

In [ ]:
%cd /content/cell_interaction_gnn/analysis/3.training_attribution/epidermis/paw/feature_ZZFR/calculate_attribution_batch
!python ./run_calculate_attribution.py

In [ ]:
%cd /content/cell_interaction_gnn/analysis/3.training_attribution/epidermis/paw/feature_ZZFR/run_analyze_prediction_performance
!python ./run_analyze_prediction_performance.py

In [ ]:
%cd /content/cell_interaction_gnn/analysis/3.training_attribution/epidermis/paw/feature_ZZFR/softmax_to_pool_attribution_batch
!python ./run_softmax_to_pool_attribution.py